title: Squadron's Nest
author: jimpri2008 GitHub User
email: jimpri2008@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Discussion for every mater takes place here!
  (You can edit this line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: unaccounted
github_username:  jimpri2008

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
